# The "display name", shown in the GitHub UI
name: Build and test

# Trigger, run on push on any branch
on:
  push:

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v5
        with: # Specify input variables to the action
          go-version: '1.21.x'

      #- run: echo "Hello world"
      #- run: go version

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test ./...
